### ISSUE TITLE
Fails to build on Ubuntu 22.04 with Python 3.10

### ISSUE THREAD

**Issue by lwbt** [MattePalte/Verbify-TTS#2]
Hello since you posted on [AskUbuntu](https://askubuntu.com/a/1419150/40581) about your project I wanted to try it out but it failed to build due to numpy not supporting 3.10. The package that caused it in the dependency chain was h5py, but even after removing the version numbers from the requirements file uit could not finish the installation, this time due to pyworld also stumbling over numpy and Python 3.10.

**Comment by MattePalte** [comment]
Hi @lwbt 
I have not tested it with 3.10. 

I have two ideas:

OPTION 1 
you can try changing the version of numpy to `1.22.0`
`NumPy 1.22.0 is a big release featuring the work of 153 contributors spread over 609 pull requests. The Python versions supported by this release are 3.8-3.10.`
Source: https://numpy.org/news/
Then you might leave some other dependencies without version number (e.g. `h5py`)
If you get it work feel free to share the modification with the community as comments or as pull request.

OPTION 2
Did you try creating a virtual environment with python3.8?
I suppose you will need to install python 3.8 system wise
```bash
sudo apt install python3.8
```
And then install everything as I did with python3.8 as replacement

I hope it helps and thanks for the interest!
I wish you a happy and productive day, 
Cheers, 
Matteo

**Comment by MattePalte** [comment]
Hi @dioniso1 how is it going?

from this [post](https://www.how2shout.com/linux/install-python-3-9-or-3-8-on-ubuntu-22-04-lts-jammy-jellyfish/) it seems it is possible.
I will close the issue for now to keep the repo clean, please reopen it if it still doesn't work.
Looking forward to your answer.

Cheers, 
Matteo
