### ISSUE TITLE
can it be used as a TTS for other programs?

### ISSUE THREAD

**Issue by hajonnes** [MattePalte/Verbify-TTS#3]
I want to use a reader called Thorium.
It applies chromium web api to see what voices are available.
Can verbify interact with chromium api or does it just read from XA_PRIMARY? 
https://github.com/edrlab/thorium-reader/discussions/1813

**Comment by MattePalte** [comment]
Hi @hajonnes thanks for the interest, 

At the moment chromium web API  is not supported, but from what I understand we would need to have an chrome extension which registers a new `chrome.ttsEngine` which calls verbify under the hood.
It seems possible. Have a look here: https://developer.chrome.com/docs/extensions/reference/ttsEngine/
At the moment it is not on the priority list, but it seems a cool idea, I'd be happy to guide you. Feel free to experiment and send a pull request when you have a working or semi-working prototype.

Thanks in advance
Cheers,
Mateo
